### ISSUE TITLE
For Your Account Security, Please Confirm Your Identity

### ISSUE THREAD

**Issue by spiveym** [karwosts/amex-offer-monitor#1]
![image](https://user-images.githubusercontent.com/15334317/63445859-c2dec680-c3fe-11e9-814e-e585418017d6.png)

Currently getting this message when using the monitor, but there's no opportunity to enter information so it will just exit and move to the next login.

**Comment by karwosts** [comment]
If you add the key "l4s: ####" to your config.yml under amex: category (replace #### with your last 4 SSN digits), the script will try to fill this form and proceed. 

Alternatively you can type it in yourself when you get this popup if you don't want to provide the information through the script. Usually when I've seen this there's a textbox right above the Continue button to type in your last 4, not sure if it's somehow missing for you, or if it's just not visible in that screenshot.

**Comment by spiveym** [comment]
Thank you. The security verification on the Amex side seems to have gone away for now so i'm not having any issues. Your first solution seems like a good idea for the future if/when it comes back.

I wasn't able to type anything in manually as the script would quit the electron browser near instantaneously when that security check appeared. I had to record my screen in order to grab the screenshot from my first post.

**Comment by spiveym** [comment]
> Thank you. The security verification on the Amex side seems to have gone away for now so i'm not having any issues. Your first solution seems like a good idea for the future if/when it comes back.
> 
> I wasn't able to type anything in manually as the script would quit the electron browser near instantaneously when that security check appeared. I had to record my screen in order to grab the screenshot from my first post.

The messages have started appearing again, and apparently I already had inserted the l4s tag and it cannot get past the security screen before quitting. I'm back to square one.

**Comment by karwosts** [comment]
Is there any errors in the console output or log that you can report?

I can help try to work through this, but might need some trial and error or
more details from your side.

**Comment by spiveym** [comment]
yup:

2019-10-12T16:42:41.856Z - info: Starting execution of amex-offer-monitor
2019-10-12T16:42:41.862Z - info: Logging into amex.com
2019-10-12T16:42:51.035Z - error:  message=amex is not defined, stack=ReferenceError: amex is not defined
    at amexLogin (C:\Users\Mark\Documents\GitHub\amex-offer-monitor\amex-offer-monitor.js:177:14)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
2019-10-12T16:42:51.381Z - info: Starting execution of amex-offer-monitor
2019-10-12T16:42:51.387Z - info: Logging into amex.com
2019-10-12T16:42:59.072Z - error:  message=amex is not defined, stack=ReferenceError: amex is not defined
    at amexLogin (C:\Users\Mark\Documents\GitHub\amex-offer-monitor\amex-offer-monitor.js:177:14)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
2019-10-12T16:42:59.428Z - info: Starting execution of amex-offer-monitor
2019-10-12T16:42:59.433Z - info: Logging into amex.com
2019-10-12T16:43:06.496Z - error:  message=amex is not defined, stack=ReferenceError: amex is not defined
    at amexLogin (C:\Users\Mark\Documents\GitHub\amex-offer-monitor\amex-offer-monitor.js:177:14)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by karwosts** [comment]
Oh I think I know this issue, I fixed it for myself a while back but forgot
to push it back to github. Try grabbing the latest version of the
amex-offer-monitor.js and see if that helps, just updated a few minutes
ago.

**Comment by spiveym** [comment]
> Oh I think I know this issue, I fixed it for myself a while back but forgot to push it back to github. Try grabbing the latest version of the amex-offer-monitor.js and see if that helps, just updated a few minutes ago.

Thanks, that worked!
