### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by ak2k** [karwosts/amex-offer-monitor#21]
Here's an extract of my execution attempt right before it fails on an error. Perhaps the site has changed, or perhaps I have more cards than the script was originally tested with?

...
Logged in and ready
Sleeping for 12.686 seconds for slowdown
Choosing a card (id = 0) ...
🚀
Ready = true
Sleeping for 26.41 seconds for slowdown
🚀
Sleeping for 20.545 seconds for slowdown
undefined
TypeError: Cannot read properties of undefined (reading '0')
    at chooseCard (/Users/a/D/amex-offer-monitor/amex-offer-monitor.js:272:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async asyncMain (/Users/a/D/amex-offer-monitor/amex-offer-monitor.js:535:28)
nightmare ended
Done with all Electron Execution. Data collected:

**Comment by karwosts** [comment]
I tried it today and it was still working ok for me. I have 8 cards on my account that I test with (4 active/4 cancelled). 

Can you describe what you see in the window when this happens? How many cards?

In my run I see it login, it clicks on the card icon that brings up the card switcher, and then we click "View All" to see the list of all cards. Then it clicks on one of the cards and continues.

Then we get to this block, which is where I guess that you are:
```

      let result = await nightmare
      .evaluate((id)=>{
        var elements = Array.from(document.querySelectorAll('header[role="listitem"]'));
        if(elements.length == 0) {
            throw "found no cards in the card switcher!"
        }
        console.log("Found " + elements.length + " cards and choosing number " + id + "\n");
        //logger.info("Found " + elements.length + " cards and choosing number " + id + "\n");
        elements[id].click();
        return [elements.length, elements[id].childNodes[0].childNodes[0].childNodes[1].innerText];
      }, cardId);
      console.dir(result);
      logger.debug(JSON.stringify(result, null, 2));
      cardcount = result[0];
      await nightmare.wait(1000);

      //if the switcher is still open, try to close it
      if(await nightmare.exists('div[id="accounts"]')) {
         console.debug("switcher is still open, attempting to close it");
         await nightmare
          .click('button[class*="axp-account-switcher"]')
          .wait(1000);
      }

      console.log("Done with chooseCard " + cardId);
```

You never get to the "Done with chooseCard" debug print, so I guess something in the DOM in the page you get to it's not matching this. Any ideas?

**Comment by ak2k** [comment]
Thank you for the reply!

It seems not to successfully click the 'View All' element and expand the
card list.

I note that if I expand the window size, and I manually click the 'View
All' in the window prior to the point the error was generated, all proceeds
normally and the expected output is generated.

When I pull the site in Firefox's inspector, I see the element
(a[title="View All"]) there, so I'm not sure why the code isn't working
as-is.

Is there something more that I can do to help troubleshoot?

**Comment by karwosts** [comment]
> It seems not to successfully click the 'View All' element and expand the card list.

And you're sure you've waited long enough? It injects a lot of random 20-30 second sleeps to try to defeat any kind of anti-bot detection (I'm not sure if such a thing exists, but when I started developing this I did everything fast and I kept getting my web access temporarily locked and special captcha-type pages thrown up). 

Going based on your log, it seems like it thinks it sucessfully clicked it, since I see after "Choosing a card two random waits, the first one is before clicking view all, and the second one is after clicking view all. If it failed to click it I don't think it would have proceeded.

After that, it dives into the DOM and gets this array:

 Array.from(document.querySelectorAll('header[role="listitem"]'
 
 It returns the array, and then tries to dereference the first item, but your log is showing it as undefined, but I can't think of why that would happen at the moment. 
 
 If you manually go to the card switcher page, click view all, and then run that command in the Developer Tools->Console, does it succesfully return an array of N items (where N is your number of cards?)
 
 If you run with  --loglevel debug, do you see anything extra of interest in your logfile?

**Comment by ak2k** [comment]
Thank you for your help!

I think you're right about the ViewAll click actually firing. What seems to
be happening is that the ViewAll button click seems to close the card
switcher carousel. Reopening the card switcher if it's closed (code below)
seems to fix my issue:

    //if there's more than 4 cards in the switcher list, expand the list to
view them all in the switcher
    await nightmare.wait(getRandomWait());
    const viewall = await nightmare.exists('a[title="View All"]');
    if(viewall) {
        await nightmare.click('a[title="View All"]').wait(500);
        await nightmare.wait(getRandomWait());
    }

    //if the switcher no longer open, try to reopen it
    if(await nightmare.exists('div[id="accounts"]')) {
    } else {
         console.debug("switcher is not open, attempting to open it");
         await nightmare
          .click('button[class*="axp-account-switcher"]')
          .wait(1000);
    }

      let result = await nightmare
      .evaluate((id)=>{
        var elements =
Array.from(document.querySelectorAll('header[role="listitem"]'));
        if(elements.length == 0) {
            throw "found no cards in the card switcher!"
        }
        console.log("Found " + elements.length + " cards and choosing
number " + id + "\n");
        //logger.info("Found " + elements.length + " cards and choosing
number " + id + "\n");
        elements[id].click();
        return [elements.length,
elements[id].childNodes[0].childNodes[0].childNodes[1].innerText];
      }, cardId);
      console.dir(result);
      logger.debug(JSON.stringify(result, null, 2));
      cardcount = result[0];
      await nightmare.wait(1000);

**Comment by karwosts** [comment]
That's pretty interesting. And when you reopen it it has the full list expanded?

I don't think you ever mentioned, how many cards are in your list? Maybe it's some odd behavior over a certain amount, though I can't think of any reason why clicking "View All" would close the entire switcher. Maybe just an odd bug on amex's side. 

Glad you found a workaround.

**Comment by ak2k** [comment]
Yes, interestingly, it keeps the list expanded.

Oops, sorry about that -- I have 8 cards in the list.

I haven't yet experimented further to see whether opening the window size
larger would cause the ViewAll click (which currently expands outside the
visible area) not to close the switcher if there's enough visible area for
all of the cards to fit on the screen.

**Comment by karwosts** [comment]
You can customize the browser height in the line where nightmare is created, though I tried creating an absurdly small window (height:200px IIRC) and it still worked for me, so I'm not sure if there's a reason why it would be different for you. 

If you want to experiment, you can try here:

    const nightmare = new Nightmare({ show: true });
    
Change to:

    const nightmare = new Nightmare({ show: true, height:1000 }); //or your desired height to test
